# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 723)
        self.btn_login = QtWidgets.QPushButton(Form)
        self.btn_login.setGeometry(QtCore.QRect(500, 40, 93, 28))
        self.btn_login.setObjectName("btn_login")
        self.ledit_ip = QtWidgets.QLineEdit(Form)
        self.ledit_ip.setGeometry(QtCore.QRect(30, 40, 113, 21))
        self.ledit_ip.setObjectName("ledit_ip")
        self.ledit_name = QtWidgets.QLineEdit(Form)
        self.ledit_name.setGeometry(QtCore.QRect(200, 40, 113, 21))
        self.ledit_name.setObjectName("ledit_name")
        self.ledit_passwd = QtWidgets.QLineEdit(Form)
        self.ledit_passwd.setGeometry(QtCore.QRect(340, 40, 113, 21))
        self.ledit_passwd.setObjectName("ledit_passwd")
        self.btn_refre = QtWidgets.QPushButton(Form)
        self.btn_refre.setGeometry(QtCore.QRect(500, 90, 93, 28))
        self.btn_refre.setObjectName("btn_refre")
        self.btn_delete = QtWidgets.QPushButton(Form)
        self.btn_delete.setGeometry(QtCore.QRect(500, 140, 93, 28))
        self.btn_delete.setObjectName("btn_delete")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(40, 120, 421, 341))
        self.listWidget.setObjectName("listWidget")
        self.btn_download = QtWidgets.QPushButton(Form)
        self.btn_download.setGeometry(QtCore.QRect(500, 230, 93, 28))
        self.btn_download.setObjectName("btn_download")
        self.btn_download_all = QtWidgets.QPushButton(Form)
        self.btn_download_all.setGeometry(QtCore.QRect(500, 270, 93, 28))
        self.btn_download_all.setObjectName("btn_download_all")
        self.btn_delete_all = QtWidgets.QPushButton(Form)
        self.btn_delete_all.setGeometry(QtCore.QRect(500, 180, 93, 28))
        self.btn_delete_all.setObjectName("btn_delete_all")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_login.setText(_translate("Form", "登录"))
        self.ledit_ip.setText(_translate("Form", "192.168.0.108"))
        self.ledit_name.setText(_translate("Form", "test1"))
        self.ledit_passwd.setText(_translate("Form", "123456"))
        self.btn_refre.setText(_translate("Form", "刷新列表"))
        self.btn_delete.setText(_translate("Form", "删除"))
        self.btn_download.setText(_translate("Form", "下载"))
        self.btn_download_all.setText(_translate("Form", "下载全部"))
        self.btn_delete_all.setText(_translate("Form", "删除全部"))
